import Config

# Configure your database
config :controlcopypasta, Controlcopypasta.Repo,
  username: "postgres",
  password: "postgres",
  hostname: "localhost",
  port: 5434,
  database: "controlcopypasta_dev",
  stacktrace: true,
  show_sensitive_data_on_connection_error: true,
  pool_size: 10

# For development, we disable any cache and enable
# debugging and code reloading.
#
# The watchers configuration can be used to run external
# watchers to your application. For example, we can use it
# to bundle .js and .css sources.
config :controlcopypasta, ControlcopypastaWeb.Endpoint,
  # Binding to 0.0.0.0 allows access from other machines on the network
  http: [ip: {0, 0, 0, 0}, port: 4000],
  check_origin: false,
  code_reloader: true,
  debug_errors: true,
  secret_key_base: "REPLACE_WITH_SECRET_KEY_BASE_FOR_DEV",
  watchers: []

# ## SSL Support
#
# In order to use HTTPS in development, a self-signed
# certificate can be generated by running the following
# Mix task:
#
#     mix phx.gen.cert
#
# Run `mix help phx.gen.cert` for more information.
#
# The `http:` config above can be replaced with:
#
#     https: [
#       port: 4001,
#       cipher_suite: :strong,
#       keyfile: "priv/cert/selfsigned_key.pem",
#       certfile: "priv/cert/selfsigned.pem"
#     ],
#
# If desired, both `http:` and `https:` keys can be
# configured to run both http and https servers on
# different ports.

# Enable dev routes for dashboard and mailbox
config :controlcopypasta, dev_routes: true

# Do not include metadata nor timestamps in development logs
config :logger, :default_formatter, format: "[$level] $message\n"

# Set a higher stacktrace during development. Avoid configuring such
# in production as building large stacktraces may be expensive.
config :phoenix, :stacktrace_depth, 20

# Initialize plugs at runtime for faster development compilation
config :phoenix, :plug_init_mode, :runtime

# CORS configuration for development - allow all origins
config :cors_plug,
  origin: ["*"],
  methods: ["GET", "POST", "PUT", "PATCH", "DELETE", "OPTIONS"],
  headers: ["Authorization", "Content-Type", "Accept", "Origin"]

# Frontend port for magic link URL construction (when Origin/Referer headers missing)
config :controlcopypasta, :frontend_port, 5173

# Swoosh mailer - use SMTP adapter for Mailhog in development
config :controlcopypasta, Controlcopypasta.Mailer,
  adapter: Swoosh.Adapters.SMTP,
  relay: System.get_env("SMTP_HOST") || "localhost",
  port: String.to_integer(System.get_env("SMTP_PORT") || "1025")

# Oban config for dev is set in runtime.exs after .env is loaded
# This allows ENABLE_SCRAPING env var to work properly
